### ISSUE TITLE
Several questions about the KernelTools

### ISSUE THREAD

**Issue by adamryczkowski** [timholy/KernelTools.jl#1]
Hello. With Julia 1.0.0 I am investigating the viability of migrating our Fortran code that does fluid dynamics into Julia. I came across your module and I have several questions.

1. Was this library ever mature enough to have any working examples of its usage? If so, can you share them (they don't have to work on the current Julia). 
2. Do you have any more documentation?
3. Do you support tiling the domain into blocks so the calculation can be done parallelly on several computing nodes (that would require a halo exchange).
4. Do you preprocess the stencil function with macros somehow?

**Comment by kmsquire** [comment]
Tim can add more details, but I believe he wrote TiledIteration.jl after this, based on the similar ideas. That library is (I believe) well maintained and widely used.

**Comment by timholy** [comment]
Thanks @kmsquire for chiming in here!

There are a couple of examples in https://github.com/timholy/HalideCall.jl. Neither package is actively maintained right now, though I've heard from a user of HalideCall that it's still working on 0.6 despite no updates in 4 years! It will need updating for 0.7, if folks find it useful.

TiledIteration is indeed newer and more modern in its design. But there's still a lot of reason to say that TiledIteration is only a small part of the solution. Instead of KernelTools I'd recommend looking at (at least) https://github.com/Jutho/TensorOperations.jl. At JuliaCon2018 @peterahrens also announced a package "Tortilla.jl" that wraps [taco](http://tensor-compiler.org/), but AFAICT that package isn't publicly available yet.

**Comment by willow-ahrens** [comment]
Awesome software here Tim! Indeed, Tortilla is a wrapper library for taco, and I am planning on some sort of beta release by the end of this semester (December). The project has grown in scope beyond a simple wrapper library, and I plan to discuss its capabilities after releasing a beta version.
